name: Test Project

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
      distribution: 'temurin'  # Specify the Java distribution
      java-version: '11'
      java-package: 'jdk'
      architecture: 'x64'

    - name: Compile Java program
      run: javac welcome.java

    - name: Run Java program
      run: java welcome